# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DepartmentReview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DepartmentReview
  pod 'Moya'

  target 'DepartmentReviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
